# perfsonar account creation

#- name: AGLT2 benchmark testing
#  include: "../../pscheduler.yml"

- name: "iteration {{ loop_number }}: set facts"
  set_fact:
    pscheduler_tasks:
      - task: latency
        source: lhcmon.bnl.gov
        #dest: psum01.aglt2.org
        dest: perfsonar-bin-arbl.umnet.umich.edu

- name: "iteration {{ loop_number }}: pScheduler testing"
  include_tasks: pscheduler_loop.yml

#
# Jem Script invoked here
#

- name: "iteration {{ loop_number }}: run script"
  #command: /lustre/umt3/user/guhitj/Gitlab/netbasilisk/XRootD/main.sh
  command: /lustre/umt3/user/guhitj/Gitlab/netbasilisk/XRootD/ansible.sh
  delegate_to: "{{ item }}"
  with_items: "{{ groups['pscheduler-hosts'] | default([]) }}"
