# perfsonar account creation

#- name: AGLT2 benchmark testing
#  include: "../../pscheduler.yml"

- name: AGLT2 facts
  set_fact:
    pscheduler_tasks:
      - task: latency
        source: lhcmon.bnl.gov
        #dest: psum01.aglt2.org
        dest: perfsonar-bin-arbl.umnet.umich.edu

- name: AGLT2 benchmark testing
  include_tasks: pscheduler.yml

#
# Jem Script invoked here
#

- name: Jem's script
  #hosts: localhost
  #tasks:
  debug:
    msg: Run Jem's script
