# perfsonar account creation

#- name: LSI benchmark testing
#  include: "../../pscheduler.yml"

- name: "iteration {{ loop_number }}: set facts"
  set_fact:
    pscheduler_tasks:
      - task: latency
        source: test10g.lsi.umich.edu 
        dest: 192.67.81.132

- name: "iteration {{ loop_number }}: pScheduler testing"
  include_tasks: pscheduler_loop.yml
  when: false
#when: false skips the perfsonar test 
#
# Jem Script invoked here
#

- name: "iteration {{ loop_number }}: run script"
  command: /lsi/groups/mcianfroccolab/zhenyutan/data_transfer.sh 
  delegate_to: "{{ item }}"
  with_items: "{{ groups['lsi-hosts'] | default([]) }}"
  register: lsi_output

- name: print lsi_output
  debug:
    var: lsi_output
