# pscheduler.yml

#- name: run perfSONAR commands
#  hosts: pscheduler-hosts
#  tasks:

#  - name: "debug info"
#    debug:
#      var: item
#    with_items: "{{ pscheduler_tasks }}"

  - name: "debug info"
    debug:
      var: item

  - name: "pscheduler task {{ item.task }} --dest {{ item.dest }} --source {{ item.source }}"
    command:
      argv:
        #- echo
        - pscheduler
        - task
        - "{{ item.task }}"
        - --dest
        - "{{ item.dest }}"
        - --source
        - "{{ item.source }}"
    register: pcheduler_output
    when: "{{ test_loop_debug | default ( True ) }}"

  - name: "pscheduler result"
    debug:
      var: pcheduler_output
    when: pcheduler_output is defined
