# pscheduler.yml

#- name: run perfSONAR commands
#  hosts: pscheduler-hosts
#  tasks:

  - name: pcheduler tasks to run
    debug:
      var: item
    with_items: "{{ pscheduler_tasks }}"

  - name: run pscheduler command
    command:
      argv:
        #- echo
        - pscheduler
        - task
        - "{{ item.task }}"
        - --dest
        - "{{ item.dest }}"
        - --source
        - "{{ item.source }}"
    with_items: "{{ pscheduler_tasks }}"
    register: pcheduler_output
    when: false

  - name: debug string
    debug:
      var: pcheduler_output
    when: pcheduler_output is defined
