# perfsonar account creation

#- name: AGLT2 benchmark testing
#  include: "../../pscheduler.yml"

- name: run pScheduler testing interlaced with test scripts
  hosts: localhost
  tasks:
  - name: "pcheduler loop testing iteration {{ item }}"
    include_tasks: "{{ test_script }}.yml"
    with_sequence: "count={{ test_loop_count | default (1) }}"
    loop_control:
      loop_var: loop_number

  - name: last pScheduler testing with aglt2 scripts
    include_tasks: pscheduler_loop.yml
